### ISSUE TITLE
power-up callback when a card-badge is clicked by a user

### ISSUE THREAD

**Issue by theguybieber** [trello/api-docs#122]
I am developing a power-up and would like to take an action when the user clicks on my power-ups card badge. Right now card badges only support a callback for periodic updating. Is there any way to do this with the current API. If not can this be added to the power-up API. It seems awkward for users to have to dig down into card back to take a simple action.

**Comment by bentleycook** [comment]
@theguybieber Unfortunately, there isn't currently a way to do this with the API. 

One of the reasons we've not added this is because it isn't something you can normally do on Trello. We've tried to keep the functionality of the client library and Power-Ups on par with the functionality of Trello's core experience. Our thinking has been that a board should give you perspective into the state of a project/board at a glance and that adding too much functionality detracts from that perspective.

That being said, I'll add this to our backlog to kick off a conversation around it. I don't know that it is something we'll add in the near future, but want to make sure we at least consider it!

**Comment by hamidp** [comment]
@theguybieber What is the scenario you're looking to support? As @bentleycook said, this is not an interaction in Trello at all so people may not even know they are able to do it. We could look at alternate additions to the platform that would solve the problem.

**Comment by theguybieber** [comment]
Thanks for the comments. I hadn't checked the discussion in a while, apologies for not getting back sooner. Let me get a little further along and we can chat.
