### ISSUE TITLE
[enhancement] user email from google login?

### ISSUE THREAD

**Issue by iBicha** [trello/api-docs#130]
I noticed that getting the email for the current user (/1/members/me) can be null.
I'm assuming in that case, that the user signed up with googe (correct me if i'm wrong)
But wouldn't it make sense to have the email saved after the oauth login?

**Comment by iBicha** [comment]
I'm probably wrong though. Is this a privacy issue then? In any case, trello should probably return at least primary email address.

**Comment by bentleycook** [comment]
@iBicha I'm not able to reproduce. You should always get back the email address when you pass in `me` to the members resource (`/1/members/me`) so long as you have a valid token.

However, `email` will be `null` if you pass in another member's ID to the endpoint: `1/members/86530f19bd582f2f01f3a8fc`. This is intentional - users' emails are not accessible.

**Comment by iBicha** [comment]
Tested with a couple of tokens, still the same
![trello api](https://cloud.githubusercontent.com/assets/17722782/26788403/4cb935e0-49ca-11e7-97d1-2a5cac48a030.png)

**Comment by iBicha** [comment]
Okey i figured it out, it was a scope related issue.
The API will only return the email if the token scope had account permission set to true.

**Comment by bentleycook** [comment]
@iBicha 👍 Good catch.

I'll update the docs and add a bit more clarification around when email is accessible.
