### ISSUE TITLE
how to create a card  and add comment to it

### ISSUE THREAD

**Issue by ewugoat7** [trello/api-docs#140]
Am trying to create card but am having error.
below is the link that i used to create card after adding my real token and api key

`https://api.trello.com/1/cards?name=my first card&desc=my first decription&key=[my api key goes here]&token=[my token goes here]`

below is the error that am having
`Cannot GET /1/cards?name........`

please what is the problem. can someone help me fix that.  Thanks

**Comment by bentleycook** [comment]
@ewugoat7 You're close! One of the most important things is that you need to `POST` to create a card. You can't do this by just typing the URL into a browser. You will need to use a tool like [`curl`](https://curl.haxx.se/) via the command line or [Postman](https://www.getpostman.com/).

Additionally, as per the [documentation for `POST 1/cards/`](https://developers.trello.com/advanced-reference/card#post-1-cards), the `idList` parameter is marked as required. Otherwise Trello doesn't know _where_ the card should go!
