### ISSUE TITLE
Can we self-host the power-up client library?

### ISSUE THREAD

**Issue by aaronjensen** [trello/api-docs#76]
The power-up client library returns cache headers that disallow caching. This means that every time a user opens a popup for our powerup they have to refetch this file, which takes time. Is there any harm in us hosting this file or bundling it and managing the caching ourselves?

**Comment by mpcowan** [comment]
Hey @aaronjensen we don't recommend self-hosting the `power-up.min.js` file that is hosted at `https://trello.com/power-ups/power-up.min.js`.

The main reason against self-hosting it is that you may miss picking up updates to it. Often this will just be new functionality, but if we have to change how some of it works under the hood to play nice with changes to Trello, then missing that could potentially break your Power-Up.

The main reason we currently aren't sending cache headers with the file is so that we can always be certain of exactly what file is being served out in the wild. I'd be interested in hearing what kind of latency you are seeing in loading that file, and if it is impacting the user experience of your Power-Up. We are definitely open to exploring ways to make the performance there better.

**Comment by aaronjensen** [comment]
Hi @mpcowan, because the main interaction points are loading iframes, every time that that iframe loads it takes the latency of the iframe html document, then on top of that the power-up.min.js (plus any of our custom js, which we *can* cache).

Here's an example from my 250mbps cable connection in Seattle for the repeating cards plugin (upon clicking on the Repeat card button):

![latency](https://cloud.githubusercontent.com/assets/8588/24014346/d1bbbd1c-0a41-11e7-874e-656173f18e28.png)

Normally I'd love for ~500ms time-to-interactive, but when it's in an app that is so responsive like Trello is it can be jarring. Also, that's a fast one. I've seen it take longer.

Compare this to our power up where we're allowing the power-up.min.js to be cached: 

![when searching display most recently touched cards on epic trello powerup trello 2017-03-16 12-15-08](https://cloud.githubusercontent.com/assets/8588/24014483/54cba370-0a42-11e7-9686-c27eecdf8185.png)

That last bit of js should be cached, but I think Chrome has heuristics that are preventing it from caching or something. 




> Often this will just be new functionality, but if we have to change how some of it works under the hood to play nice with changes to Trello, then missing that could potentially break your Power-Up.

We're updating it every time we deploy a new version, but yes, I can see how this could get stale and potentially break. I assume that the red "Reload" button on trello helps to keep this up to date if breaking changes do occur?

Btw, we're really impressed w/ the power-up api. It's great to be able to do so much with it. Nice work!

**Comment by bentleycook** [comment]
To summarize, our current recommendation is not to self-host the file as we do update it fairly often. However, we understand the speed implications with no caching and will add it as a to-do in our backlog.
