### ISSUE TITLE
How do I get the last modified date for a card from the power up api?

### ISSUE THREAD

**Issue by aaronjensen** [trello/api-docs#81]
This seems to be available from the actual api, but the power-up api doesn't include it. It'd be helpful for us so that we can sort cards by most recently used. Thanks!

**Comment by bentleycook** [comment]
Not something we had in our backlog, but we've added it. I'll update this issue whenever we make some progress on it. Thanks @aaronjensen!

**Comment by aaronjensen** [comment]
Thanks! We'd also like members avatar urls if possible, would you like me to open a separate issue for that?

**Comment by bentleycook** [comment]
@aaronjensen You should be able to use t.member:

```t.member Accepted fields: 'id', 'fullName', 'username', 'avatar'. This is an easy way to get information about active members. 'avatar' returns the complete URL for the 50px png file.```

**Comment by aaronjensen** [comment]
Am I only able to get the current user's avatar? I don't remember seeing `avatar` in the members of a card if I use `t.card`

**Comment by bentleycook** [comment]
Correct, you can only get the current user's avatar. I'm guessing you are trying to grab other users' avatars as well? In that case, since it isn't possible with the client library, the members endpoint is the way to go: https://developers.trello.com/advanced-reference/member Though this would require you to ask the user to authorize so that you can get their token.

**Comment by bentleycook** [comment]
Closing as we added dateLastActivity. Ping me if you've got a question on member avatars.
